# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XVugXTayp4-TnIiZnFdtxRd-SVjdRKfp
"""

import pandas as pd

def analyze_housing_data():
    # Load affordable housing project data
    affordable_housing = pd.read_csv("affordable_housing.csv")

    # Load ward populations
    ward_populations = pd.read_csv("Wards_from_2022.csv")

    # Join population data to affordable housing data
    housing_with_population = pd.merge(affordable_housing, ward_populations[['NAME','POP100','HU100']], left_on='MAR_WARD', right_on='NAME')

    # Calculate proportion of housing units per population
    housing_with_population['prop_housing_units'] = housing_with_population['HU100'] / housing_with_population['POP100']
    # Calculate the mean ratio for all wards
    mean_ratio = housing_with_population['prop_housing_units'].mean()

    # Identify wards with ratios significantly higher or lower than the mean
    disproportionately_large = housing_with_population[housing_with_population['prop_housing_units'] > mean_ratio]
    disproportionately_small = housing_with_population[housing_with_population['prop_housing_units'] < mean_ratio]

    return mean_ratio, disproportionately_large, disproportionately_small